

name: dbt_reporting
version: 1.0

profile: grazitti_interactive

source-paths: ["models"]
target-path: "target"

models:
  tps_reporting:
    github:
      base:
        materialized: event_email_summary
